### ISSUE TITLE
does not build on a clean Ubuntu 16

### ISSUE THREAD

**Issue by mkim3000** [spring-cloud/spring-cloud-spinnaker#34]
_./build_spinnaker.sh all_ does not complete without error unless bower and nodejs (with npm) installed beforehand.  Either update the README.md or add as part of the installation script(s).

**Comment by gregturn** [comment]
Ah yes, I forgot that deck requires bower and node, and isn't covered by the main project's frontend-maven-plugin. Figuring out how to work around will be quite tricky.

**Comment by gregturn** [comment]
This issue will be resolved when we are able to stop building Spinnaker's modules inside this project, and instead consume them from maven central.

/cc @markpollack

**Comment by gregturn** [comment]
Overcome by the fact we don't build Spinnaker modules anymore.

**Comment by markpollack** [comment]
```[INFO] Unpacking /home/mpollack/projects/spring-cloud-spinnaker/target/npm.tar.gz into /home/mpollack/projects/spring-cloud-spinnaker/target/node/node_modules
[INFO] Installed NPM locally.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.28:npm (npm install) @ spring-cloud-spinnaker ---
[INFO] Found proxies: []
[INFO] Running 'npm install' in /home/mpollack/projects/spring-cloud-spinnaker
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.28:bower (bower install) @ spring-cloud-spinnaker ---
[INFO] Found proxies: []
[INFO] Running 'bower install' in /home/mpollack/projects/spring-cloud-spinnaker
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'q'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/home/mpollack/projects/spring-cloud-spinnaker/node_modules/bower/lib/bin/bower.js:3:9)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
``` is the current behavior on ubuntu 16.04
